version: "3.9"


services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    command: ["--auth"]
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
    - ./mongo/initdb:/docker-entrypoint-initdb.d:ro
    - mongo_data:/data/db


  migrator:
    build: ./migrator
    container_name: migrator
    depends_on:
    - mongodb
    environment:
      MONGO_URI: ${MONGO_URI}
      DATA_FILE: ${DATA_FILE}
    volumes:
    - ./data:/app/data:ro
    # By default, do nothing; run it on demand with `docker compose run --rm migrator`
    entrypoint: ["python", "migrate.py"]


volumes:
  mongo_data: