services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}

  fastapi:
    build:
      context: ./backend
      dockerfile: Dockerfileapi
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
      - images:/images
    depends_on:
      - mongodb
    environment:
      - ENV=production



volumes:
  mongodb-data:
  images: